### ISSUE TITLE
Python Version Mismatch (Expected: 3.11, Actual: 3.10.12)

### ISSUE THREAD

**Issue by NisuSan** [ai-dock/jupyter-python#1]
The Python version within the Docker image is expected to be **3.11**, but upon inspection within the container, it's identified as **3.10.12.**

**Steps to Reproduce:**

1. Pull the Docker image ```docker pull ghcr.io/ai-dock/jupyter-python:3.11-cuda-12.2.0-runtime-22.04```.
2. Run the Docker container.
3. Check the Python version inside the container using the command ```python3 --version```.

**Expected Behavior:**
The Python version within the Docker image should match the specified requirement of 3.11.

**Actual Behavior:**
The Python version inside the Docker container is reported as 3.10.12, which deviates from the expected 3.11 version.

**Comment by robballantyne** [comment]
Are you working from within the python_311 mamba environment? It should have been automatically activated on login.

The image contains 3.10.12 installed by apt-get but when inside the environment python3 will be mapped to /opt/micromamba/envs/python_311/bin/python3

**Comment by robballantyne** [comment]
Container provides the correct version of Python as documented.
